# wordpress-pv.yaml
apiVersion: v1
kind: PersistentVolume # Indica que es crea un Volum Persistent.
metadata:
  name: wordpress-pv # Nom únic per al PV dins del clúster.
spec:
  accessModes:
    - ReadWriteOnce # El volum pot ser muntat en lectura/escriptura per un sol node.
  capacity:
    storage: 1Gi # Defineix la capacitat d'emmagatzematge del volum, 1 gigabyte.
  persistentVolumeReclaimPolicy: Retain # Quan la PVC és eliminada, el PV no serà eliminat i les dades seran retingudes.
  hostPath:
    path: "/mnt/data/wordpress" # Especifica la ruta en el node on s'emmagatzemen les dades del volum.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi