apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          value: "password1234"
        - name: WORDPRESS_DB_USER
          value: "wpuser"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        ports:
          - containerPort: 80
            name: wordpress
        volumeMounts:
        - name: wordpress-pv-claim
          mountPath: /var/www/html
      volumes:
      - name: wordpress-pv-claim
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
