# mysql-pv.yaml
apiVersion: v1
kind: PersistentVolume # Especifica el tipus de recurs que s'està creant, en aquest cas, un volum persistent.
metadata:
  name: mysql-pv # Aquesta és la identificació única dins del clúster per al PV.
spec:
  accessModes:
    - ReadWriteOnce # Això indica el mode d'accés al volum. ReadWriteOnce significa que el volum pot ser muntat com a lectura/escriptura per un únic node.
  capacity:
    storage: 2Gi # Defineix la capacitat del volum, en aquest cas, 2 gigabytes.
  persistentVolumeReclaimPolicy: Retain # Quan la PVC és eliminada, el PV no serà eliminat i les dades seran retingudes.
  hostPath:
    path: "/mnt/data/mysql" # Especifica la ruta en el node on s'emmagatzemen les dades del volum.

---
# Les PVCs permeten a l'usuari reclamar recursos d'emmagatzematge específics definits en els PVs segons les seves necessitats.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi


